import { MongoClient } from 'mongodb';
import 'dotenv/config';

// 카테고리별 이미지 맵
const categoryImages = {
  diet: '/images/category/diet.png',
  eye: '/images/category/eye_health.png',
  gut: '/images/category/gut_health.png',
  immune_fatigue: '/images/category/immune_energe.png',
  skin_hair: '/images/category/skin_hair.png',
  women: '/images/category/womens_health.png',
  brain: '/images/category/brain_focus.png',
  blood_flow: '/images/category/circulation.png',
  bone_joint: '/images/category/bone_joint.png',
  general: '/images/category/general.png',
};

// products 배열
const products = [
  {
    _id: 1,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'diet_garcinia',
    categoryId: 'diet',
    name: '가르시니아 캄보지아',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['HCA'],
    mainFunctions: ['탄수화물의 지방 전환 억제', '체지방 감소'],
    intakeGuide: '식사 30분 전 섭취',
    precautions: ['위장 장애 주의', '임산부 섭취 금지'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '750mg', nutrients: [{ name: 'HCA', amount: '750mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 6000,
    quantity: 600,
    show: true,
    active: true,
    views: 8,
  },
  {
    _id: 2,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'general_multivitamin',
    categoryId: 'general',
    name: '종합비타민',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['비타민 A', 'B군', 'C', 'D', 'E'],
    mainFunctions: ['전반적인 건강 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['다른 비타민과 중복 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '비타민 복합', amount: '-', dailyValue: '-' }] },
    seller_id: 1,
    price: 18000,
    quantity: 600,
    show: true,
    active: true,
    views: 4,
  },
  {
    _id: 3,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'diet_garcinia',
    categoryId: 'diet',
    name: '가르시니아 캄보지아',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['HCA'],
    mainFunctions: ['탄수화물의 지방 전환 억제', '체지방 감소'],
    intakeGuide: '식사 30분 전 섭취',
    precautions: ['위장 장애 주의', '임산부 섭취 금지'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '750mg', nutrients: [{ name: 'HCA', amount: '750mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 6000,
    quantity: 600,
    show: true,
    active: true,
    views: 3,
  },
  {
    _id: 4,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'diet_garcinia',
    categoryId: 'diet',
    name: '비타민 C',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['HCA'],
    mainFunctions: ['탄수화물의 지방 전환 억제', '체지방 감소'],
    intakeGuide: '식사 30분 전 섭취',
    precautions: ['위장 장애 주의', '임산부 섭취 금지'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '750mg', nutrients: [{ name: 'HCA', amount: '750mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 6000,
    quantity: 600,
    show: true,
    active: true,
    views: 28,
  },
  {
    _id: 5,
    createdAt: '2026.02.02 01:00:00',
    updatedAt: '2026.02.02 01:00:00',
    mainId: 'diet_lcarnitine',
    categoryId: 'diet',
    name: 'L-카르니틴',
    content: '체지방 연소에 도움을 주는 영양제입니다.',
    mainNutrients: ['L-Carnitine'],
    mainFunctions: ['지방 연소 촉진', '체지방 감소'],
    intakeGuide: '운동 30분 전 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '500mg', nutrients: [{ name: 'L-Carnitine', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 8000,
    quantity: 500,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 6,
    createdAt: '2026.02.02 01:05:00',
    updatedAt: '2026.02.02 01:05:00',
    mainId: 'eye_lutein',
    categoryId: 'eye',
    name: '루테인 플러스',
    content: '눈 건강에 도움을 주는 루테인 영양제',
    mainNutrients: ['루테인', '지아잔틴'],
    mainFunctions: ['눈 피로 완화', '시력 보호'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '500mg', nutrients: [{ name: '루테인', amount: '10mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 12000,
    quantity: 400,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 7,
    createdAt: '2026.02.02 01:06:00',
    updatedAt: '2026.02.02 01:06:00',
    mainId: 'eye_zeaxanthin',
    categoryId: 'eye',
    name: '지아잔틴 아이케어',
    content: '눈 건강에 도움을 주는 지아잔틴 영양제',
    mainNutrients: ['지아잔틴'],
    mainFunctions: ['눈 피로 완화', '야간 시력 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['임산부 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '400mg', nutrients: [{ name: '지아잔틴', amount: '10mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 15000,
    quantity: 350,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 8,
    createdAt: '2026.02.02 01:07:00',
    updatedAt: '2026.02.02 01:07:00',
    mainId: 'gut_probiotics',
    categoryId: 'gut',
    name: '프로바이오틱스',
    content: '장 건강에 도움을 주는 유산균',
    mainNutrients: ['유산균'],
    mainFunctions: ['장 건강 개선', '소화 촉진'],
    intakeGuide: '식후 섭취',
    precautions: ['냉장 보관 권장'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1캡슐', nutrients: [{ name: '유산균', amount: '10억 CFU', dailyValue: '-' }] },
    seller_id: 1,
    price: 18000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 9,
    createdAt: '2026.02.02 01:08:00',
    updatedAt: '2026.02.02 01:08:00',
    mainId: 'gut_fiber',
    categoryId: 'gut',
    name: '식이섬유 보충제',
    content: '장 건강을 위한 식이섬유',
    mainNutrients: ['식이섬유'],
    mainFunctions: ['배변 활동 개선', '장 건강 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '2정', nutrients: [{ name: '식이섬유', amount: '5g', dailyValue: '50%' }] },
    seller_id: 1,
    price: 10000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 10,
    createdAt: '2026.02.02 01:09:00',
    updatedAt: '2026.02.02 01:09:00',
    mainId: 'immune_vitc',
    categoryId: 'immune_fatigue',
    name: '비타민 C 1000mg',
    content: '면역력 증진에 도움을 주는 비타민 C',
    mainNutrients: ['비타민 C'],
    mainFunctions: ['면역력 강화', '피로 회복'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '비타민 C', amount: '1000mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 9000,
    quantity: 400,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 11,
    createdAt: '2026.02.02 01:10:00',
    updatedAt: '2026.02.02 01:10:00',
    mainId: 'immune_zinc',
    categoryId: 'immune_fatigue',
    name: '아연 플러스',
    content: '면역력과 피로 회복에 도움',
    mainNutrients: ['아연'],
    mainFunctions: ['면역력 강화', '피로 회복'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '아연', amount: '15mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 10000,
    quantity: 350,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 12,
    createdAt: '2026.02.02 01:11:00',
    updatedAt: '2026.02.02 01:11:00',
    mainId: 'skin_collagen',
    categoryId: 'skin_hair',
    name: '콜라겐 앰플',
    content: '피부 탄력 및 모발 건강 지원',
    mainNutrients: ['콜라겐'],
    mainFunctions: ['피부 탄력 개선', '모발 건강 지원'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1포', nutrients: [{ name: '콜라겐', amount: '1000mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 25000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 13,
    createdAt: '2026.02.02 01:12:00',
    updatedAt: '2026.02.02 01:12:00',
    mainId: 'skin_hair_biotin',
    categoryId: 'skin_hair',
    name: '비오틴 플러스',
    content: '모발과 피부 건강 지원',
    mainNutrients: ['비오틴'],
    mainFunctions: ['모발 강화', '피부 건강 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '비오틴', amount: '500mcg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 18000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 14,
    createdAt: '2026.02.02 01:13:00',
    updatedAt: '2026.02.02 01:13:00',
    mainId: 'woman_folic',
    categoryId: 'women',
    name: '엽산 플러스',
    content: '여성 건강 지원 영양제',
    mainNutrients: ['엽산'],
    mainFunctions: ['임산부 건강', '빈혈 예방'],
    intakeGuide: '식후 섭취',
    precautions: ['임신 계획 여성 권장'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '엽산', amount: '400mcg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 12000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 15,
    createdAt: '2026.02.02 01:14:00',
    updatedAt: '2026.02.02 01:14:00',
    mainId: 'woman_iron',
    categoryId: 'women',
    name: '철분 플러스',
    content: '여성 건강 및 빈혈 예방',
    mainNutrients: ['철분'],
    mainFunctions: ['빈혈 예방', '체력 증진'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '철분', amount: '15mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 12000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 16,
    createdAt: '2026.02.02 01:15:00',
    updatedAt: '2026.02.02 01:15:00',
    mainId: 'brain_ginkgo',
    categoryId: 'brain',
    name: '은행잎 추출물',
    content: '뇌•집중력 개선 영양제',
    mainNutrients: ['Ginkgo Biloba'],
    mainFunctions: ['기억력 개선', '집중력 향상'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: 'Ginkgo Biloba', amount: '120mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 18000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 17,
    createdAt: '2026.02.02 01:16:00',
    updatedAt: '2026.02.02 01:16:00',
    mainId: 'brain_phosphatidylserine',
    categoryId: 'brain',
    name: '포스파티딜세린',
    content: '뇌•집중력 개선 영양제',
    mainNutrients: ['Phosphatidylserine'],
    mainFunctions: ['기억력 개선', '집중력 향상'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '100mg', nutrients: [{ name: 'Phosphatidylserine', amount: '100mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 22000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 18,
    createdAt: '2026.02.02 01:17:00',
    updatedAt: '2026.02.02 01:17:00',
    mainId: 'blood_ginkgo',
    categoryId: 'blood_flow',
    name: '혈액순환 개선제',
    content: '혈액순환 개선에 도움',
    mainNutrients: ['Ginkgo Biloba'],
    mainFunctions: ['혈액순환 개선', '피로 회복'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: 'Ginkgo Biloba', amount: '120mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 20000,
    quantity: 150,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 19,
    createdAt: '2026.02.02 01:18:00',
    updatedAt: '2026.02.02 01:18:00',
    mainId: 'blood_omega3',
    categoryId: 'blood_flow',
    name: '오메가3',
    content: '혈액순환과 심혈관 건강 지원',
    mainNutrients: ['EPA', 'DHA'],
    mainFunctions: ['혈액순환 개선', '심혈관 건강 지원'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1캡슐', nutrients: [{ name: 'EPA+DHA', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 25000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 20,
    createdAt: '2026.02.02 01:19:00',
    updatedAt: '2026.02.02 01:19:00',
    mainId: 'bone_calcium',
    categoryId: 'bone_joint',
    name: '칼슘 마그네슘',
    content: '뼈와 관절 건강 지원',
    mainNutrients: ['칼슘', '마그네슘'],
    mainFunctions: ['뼈 건강 유지', '관절 건강 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '2정', nutrients: [{ name: '칼슘+마그네슘', amount: '1000mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 18000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 21,
    createdAt: '2026.02.02 01:20:00',
    updatedAt: '2026.02.02 01:20:00',
    mainId: 'bone_glucosamine',
    categoryId: 'bone_joint',
    name: '글루코사민 플러스',
    content: '관절 건강 지원',
    mainNutrients: ['글루코사민', '콘드로이틴'],
    mainFunctions: ['관절 건강 개선', '연골 보호'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '글루코사민', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 22000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 22,
    createdAt: '2026.02.02 01:21:00',
    updatedAt: '2026.02.02 01:21:00',
    mainId: 'diet_omega3',
    categoryId: 'diet',
    name: '오메가3 다이어트',
    content: '체지방 감소와 건강 지원',
    mainNutrients: ['EPA', 'DHA'],
    mainFunctions: ['체지방 감소', '혈행 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1캡슐', nutrients: [{ name: 'EPA+DHA', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 20000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
];

// 이미지 URL 자동 연결
const productsWithImages = products.map((p) => ({
  ...p,
  imageUrl: categoryImages[p.categoryId] || '/images/category/general.png',
}));

async function main() {
  const client = new MongoClient(process.env.MONGO_URI);
  await client.connect();
  const db = client.db('febc15-final05-ecad');
  const collection = db.collection('product');

  // 기존 데이터 삭제 (테스트용)
  await collection.deleteMany({});

  // 데이터 삽입
  const result = await collection.insertMany(productsWithImages);
  console.log(`${result.insertedCount}개의 상품이 삽입되었습니다.`);

  await client.close();
}

main().catch(console.error);
