import { MongoClient } from 'mongodb';
import 'dotenv/config';

// 실행방법 : node scripts/seed.js 실행 시 몽고DB에 데이터 초기화 후 수정된 현재 데이터 삽입

// 카테고리별 이미지 맵
const categoryImages = {
  diet: '/images/category/diet.png',
  eye: '/images/category/eye_health.png',
  gut: '/images/category/gut_health.png',
  immune_fatigue: '/images/category/immune_energy.png',
  skin_hair: '/images/category/skin_hair.png',
  women: '/images/category/womens_health.png',
  brain: '/images/category/brain_focus.png',
  blood_flow: '/images/category/circulation.png',
  bone_joint: '/images/category/bone_joint.png',
  general: '/images/category/general.png',
};

// products 배열
const products = [
  {
    _id: 1,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'diet_garcinia',
    categoryId: 'diet',
    name: '가르시니아 캄보지아',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['HCA'],
    mainFunctions: ['탄수화물의 지방 전환 억제', '체지방 감소'],
    intakeGuide: '식사 30분 전 섭취',
    precautions: ['위장 장애 주의', '임산부 섭취 금지'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '750mg', nutrients: [{ name: 'HCA', amount: '750mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 6000,
    quantity: 600,
    show: true,
    active: true,
    views: 8,
  },
  {
    _id: 2,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'general_multivitamin',
    categoryId: 'general',
    name: '종합비타민',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['비타민 A', 'B군', 'C', 'D', 'E'],
    mainFunctions: ['전반적인 건강 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['다른 비타민과 중복 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '비타민 복합', amount: '-', dailyValue: '-' }] },
    seller_id: 1,
    price: 18000,
    quantity: 600,
    show: true,
    active: true,
    views: 4,
  },
  {
    _id: 3,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'diet_garcinia',
    categoryId: 'diet',
    name: '가르시니아 캄보지아',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['HCA'],
    mainFunctions: ['탄수화물의 지방 전환 억제', '체지방 감소'],
    intakeGuide: '식사 30분 전 섭취',
    precautions: ['위장 장애 주의', '임산부 섭취 금지'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '750mg', nutrients: [{ name: 'HCA', amount: '750mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 6000,
    quantity: 600,
    show: true,
    active: true,
    views: 3,
  },
  {
    _id: 4,
    createdAt: '2026.02.02 00:29:31',
    updatedAt: '2026.02.02 00:29:31',
    mainId: 'diet_garcinia',
    categoryId: 'diet',
    name: '비타민 C',
    content: '영양제를 드셔보세요!',
    mainNutrients: ['HCA'],
    mainFunctions: ['탄수화물의 지방 전환 억제', '체지방 감소'],
    intakeGuide: '식사 30분 전 섭취',
    precautions: ['위장 장애 주의', '임산부 섭취 금지'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '750mg', nutrients: [{ name: 'HCA', amount: '750mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 6000,
    quantity: 600,
    show: true,
    active: true,
    views: 28,
  },
  {
    _id: 5,
    createdAt: '2026.02.02 01:00:00',
    updatedAt: '2026.02.02 01:00:00',
    mainId: 'diet_lcarnitine',
    categoryId: 'diet',
    name: 'L-카르니틴',
    content: '체지방 연소에 도움을 주는 영양제입니다.',
    mainNutrients: ['L-Carnitine'],
    mainFunctions: ['지방 연소 촉진', '체지방 감소'],
    intakeGuide: '운동 30분 전 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘하고 건조한 곳',
    nutritionInfoExample: { servingSize: '500mg', nutrients: [{ name: 'L-Carnitine', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 8000,
    quantity: 500,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 6,
    createdAt: '2026.02.02 01:05:00',
    updatedAt: '2026.02.02 01:05:00',
    mainId: 'eye_lutein',
    categoryId: 'eye',
    name: '루테인 플러스',
    content: '눈 건강에 도움을 주는 루테인 영양제',
    mainNutrients: ['루테인', '지아잔틴'],
    mainFunctions: ['눈 피로 완화', '시력 보호'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '500mg', nutrients: [{ name: '루테인', amount: '10mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 12000,
    quantity: 400,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 7,
    createdAt: '2026.02.02 01:06:00',
    updatedAt: '2026.02.02 01:06:00',
    mainId: 'eye_zeaxanthin',
    categoryId: 'eye',
    name: '지아잔틴 아이케어',
    content: '눈 건강에 도움을 주는 지아잔틴 영양제',
    mainNutrients: ['지아잔틴'],
    mainFunctions: ['눈 피로 완화', '야간 시력 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['임산부 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '400mg', nutrients: [{ name: '지아잔틴', amount: '10mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 15000,
    quantity: 350,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 8,
    createdAt: '2026.02.02 01:07:00',
    updatedAt: '2026.02.02 01:07:00',
    mainId: 'gut_probiotics',
    categoryId: 'gut',
    name: '프로바이오틱스',
    content: '장 건강에 도움을 주는 유산균',
    mainNutrients: ['유산균'],
    mainFunctions: ['장 건강 개선', '소화 촉진'],
    intakeGuide: '식후 섭취',
    precautions: ['냉장 보관 권장'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1캡슐', nutrients: [{ name: '유산균', amount: '10억 CFU', dailyValue: '-' }] },
    seller_id: 1,
    price: 18000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 9,
    createdAt: '2026.02.02 01:08:00',
    updatedAt: '2026.02.02 01:08:00',
    mainId: 'gut_fiber',
    categoryId: 'gut',
    name: '식이섬유 보충제',
    content: '장 건강을 위한 식이섬유',
    mainNutrients: ['식이섬유'],
    mainFunctions: ['배변 활동 개선', '장 건강 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '2정', nutrients: [{ name: '식이섬유', amount: '5g', dailyValue: '50%' }] },
    seller_id: 1,
    price: 10000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 10,
    createdAt: '2026.02.02 01:09:00',
    updatedAt: '2026.02.02 01:09:00',
    mainId: 'immune_vitc',
    categoryId: 'immune_fatigue',
    name: '비타민 C 1000mg',
    content: '면역력 증진에 도움을 주는 비타민 C',
    mainNutrients: ['비타민 C'],
    mainFunctions: ['면역력 강화', '피로 회복'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '비타민 C', amount: '1000mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 9000,
    quantity: 400,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 11,
    createdAt: '2026.02.02 01:10:00',
    updatedAt: '2026.02.02 01:10:00',
    mainId: 'immune_zinc',
    categoryId: 'immune_fatigue',
    name: '아연 플러스',
    content: '면역력과 피로 회복에 도움',
    mainNutrients: ['아연'],
    mainFunctions: ['면역력 강화', '피로 회복'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '아연', amount: '15mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 10000,
    quantity: 350,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 12,
    createdAt: '2026.02.02 01:11:00',
    updatedAt: '2026.02.02 01:11:00',
    mainId: 'skin_collagen',
    categoryId: 'skin_hair',
    name: '콜라겐 앰플',
    content: '피부 탄력 및 모발 건강 지원',
    mainNutrients: ['콜라겐'],
    mainFunctions: ['피부 탄력 개선', '모발 건강 지원'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1포', nutrients: [{ name: '콜라겐', amount: '1000mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 25000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 13,
    createdAt: '2026.02.02 01:12:00',
    updatedAt: '2026.02.02 01:12:00',
    mainId: 'skin_hair_biotin',
    categoryId: 'skin_hair',
    name: '비오틴 플러스',
    content: '모발과 피부 건강 지원',
    mainNutrients: ['비오틴'],
    mainFunctions: ['모발 강화', '피부 건강 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '비오틴', amount: '500mcg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 18000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 14,
    createdAt: '2026.02.02 01:13:00',
    updatedAt: '2026.02.02 01:13:00',
    mainId: 'woman_folic',
    categoryId: 'women',
    name: '엽산 플러스',
    content: '여성 건강 지원 영양제',
    mainNutrients: ['엽산'],
    mainFunctions: ['임산부 건강', '빈혈 예방'],
    intakeGuide: '식후 섭취',
    precautions: ['임신 계획 여성 권장'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '엽산', amount: '400mcg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 12000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 15,
    createdAt: '2026.02.02 01:14:00',
    updatedAt: '2026.02.02 01:14:00',
    mainId: 'woman_iron',
    categoryId: 'women',
    name: '철분 플러스',
    content: '여성 건강 및 빈혈 예방',
    mainNutrients: ['철분'],
    mainFunctions: ['빈혈 예방', '체력 증진'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '철분', amount: '15mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 12000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 16,
    createdAt: '2026.02.02 01:15:00',
    updatedAt: '2026.02.02 01:15:00',
    mainId: 'brain_ginkgo',
    categoryId: 'brain',
    name: '은행잎 추출물',
    content: '뇌•집중력 개선 영양제',
    mainNutrients: ['Ginkgo Biloba'],
    mainFunctions: ['기억력 개선', '집중력 향상'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: 'Ginkgo Biloba', amount: '120mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 18000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 17,
    createdAt: '2026.02.02 01:16:00',
    updatedAt: '2026.02.02 01:16:00',
    mainId: 'brain_phosphatidylserine',
    categoryId: 'brain',
    name: '포스파티딜세린',
    content: '뇌•집중력 개선 영양제',
    mainNutrients: ['Phosphatidylserine'],
    mainFunctions: ['기억력 개선', '집중력 향상'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '100mg', nutrients: [{ name: 'Phosphatidylserine', amount: '100mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 22000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 18,
    createdAt: '2026.02.02 01:17:00',
    updatedAt: '2026.02.02 01:17:00',
    mainId: 'blood_ginkgo',
    categoryId: 'blood_flow',
    name: '혈액순환 개선제',
    content: '혈액순환 개선에 도움',
    mainNutrients: ['Ginkgo Biloba'],
    mainFunctions: ['혈액순환 개선', '피로 회복'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 복용 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: 'Ginkgo Biloba', amount: '120mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 20000,
    quantity: 150,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 19,
    createdAt: '2026.02.02 01:18:00',
    updatedAt: '2026.02.02 01:18:00',
    mainId: 'blood_omega3',
    categoryId: 'blood_flow',
    name: '오메가3',
    content: '혈액순환과 심혈관 건강 지원',
    mainNutrients: ['EPA', 'DHA'],
    mainFunctions: ['혈액순환 개선', '심혈관 건강 지원'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1캡슐', nutrients: [{ name: 'EPA+DHA', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 25000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 20,
    createdAt: '2026.02.02 01:19:00',
    updatedAt: '2026.02.02 01:19:00',
    mainId: 'bone_calcium',
    categoryId: 'bone_joint',
    name: '칼슘 마그네슘',
    content: '뼈와 관절 건강 지원',
    mainNutrients: ['칼슘', '마그네슘'],
    mainFunctions: ['뼈 건강 유지', '관절 건강 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '2정', nutrients: [{ name: '칼슘+마그네슘', amount: '1000mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 18000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 21,
    createdAt: '2026.02.02 01:20:00',
    updatedAt: '2026.02.02 01:20:00',
    mainId: 'bone_glucosamine',
    categoryId: 'bone_joint',
    name: '글루코사민 플러스',
    content: '관절 건강 지원',
    mainNutrients: ['글루코사민', '콘드로이틴'],
    mainFunctions: ['관절 건강 개선', '연골 보호'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1정', nutrients: [{ name: '글루코사민', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 22000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 22,
    createdAt: '2026.02.02 01:21:00',
    updatedAt: '2026.02.02 01:21:00',
    mainId: 'diet_omega3',
    categoryId: 'diet',
    name: '오메가3 다이어트',
    content: '체지방 감소와 건강 지원',
    mainNutrients: ['EPA', 'DHA'],
    mainFunctions: ['체지방 감소', '혈행 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: { servingSize: '1캡슐', nutrients: [{ name: 'EPA+DHA', amount: '500mg', dailyValue: '100%' }] },
    seller_id: 1,
    price: 20000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 23,
    createdAt: '2026.02.02 02:00:00',
    updatedAt: '2026.02.02 02:00:00',
    mainId: 'diet_green_tea',
    categoryId: 'diet',
    name: '녹차 추출물',
    content: '체지방 감소에 도움을 주는 녹차 카테킨',
    mainNutrients: ['카테킨'],
    mainFunctions: ['체지방 감소', '항산화 작용'],
    intakeGuide: '식후 섭취',
    precautions: ['카페인 민감자 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '500mg',
      nutrients: [{ name: '카테킨', amount: '300mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 14000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 24,
    createdAt: '2026.02.02 02:01:00',
    updatedAt: '2026.02.02 02:01:00',
    mainId: 'eye_astaxanthin',
    categoryId: 'eye',
    name: '아스타잔틴',
    content: '눈 피로 개선에 도움을 주는 항산화 성분',
    mainNutrients: ['아스타잔틴'],
    mainFunctions: ['눈 피로 완화', '항산화'],
    intakeGuide: '식후 섭취',
    precautions: ['임산부 섭취 전 상담'],
    storage: '직사광선 피해 보관',
    nutritionInfoExample: {
      servingSize: '6mg',
      nutrients: [{ name: '아스타잔틴', amount: '6mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 22000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 25,
    createdAt: '2026.02.02 02:02:00',
    updatedAt: '2026.02.02 02:02:00',
    mainId: 'gut_enzyme',
    categoryId: 'gut',
    name: '소화 효소 플러스',
    content: '소화를 돕는 복합 효소',
    mainNutrients: ['소화효소'],
    mainFunctions: ['소화 촉진', '복부 불편 완화'],
    intakeGuide: '식사 직후 섭취',
    precautions: ['위염 환자 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1정',
      nutrients: [{ name: '소화효소', amount: '-', dailyValue: '-' }],
    },
    seller_id: 1,
    price: 13000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 26,
    createdAt: '2026.02.02 02:03:00',
    updatedAt: '2026.02.02 02:03:00',
    mainId: 'immune_beta_glucan',
    categoryId: 'immune_fatigue',
    name: '베타글루칸',
    content: '면역 기능 증진에 도움',
    mainNutrients: ['베타글루칸'],
    mainFunctions: ['면역력 강화'],
    intakeGuide: '식후 섭취',
    precautions: ['자가면역 질환자 상담 필요'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '250mg',
      nutrients: [{ name: '베타글루칸', amount: '250mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 17000,
    quantity: 220,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 27,
    createdAt: '2026.02.02 02:04:00',
    updatedAt: '2026.02.02 02:04:00',
    mainId: 'skin_hyaluronic',
    categoryId: 'skin_hair',
    name: '히알루론산',
    content: '피부 보습과 탄력 유지',
    mainNutrients: ['히알루론산'],
    mainFunctions: ['피부 보습', '피부 탄력'],
    intakeGuide: '취침 전 섭취',
    precautions: ['특이 체질 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '120mg',
      nutrients: [{ name: '히알루론산', amount: '120mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 19000,
    quantity: 240,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 28,
    createdAt: '2026.02.02 02:05:00',
    updatedAt: '2026.02.02 02:05:00',
    mainId: 'women_gla',
    categoryId: 'women',
    name: '감마리놀렌산',
    content: '여성 호르몬 균형과 피부 건강',
    mainNutrients: ['GLA'],
    mainFunctions: ['여성 건강', '피부 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['임산부 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '320mg',
      nutrients: [{ name: 'GLA', amount: '320mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 21000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 29,
    createdAt: '2026.02.02 02:06:00',
    updatedAt: '2026.02.02 02:06:00',
    mainId: 'brain_l_theanine',
    categoryId: 'brain',
    name: 'L-테아닌',
    content: '집중력과 심리적 안정에 도움',
    mainNutrients: ['L-테아닌'],
    mainFunctions: ['집중력 향상', '스트레스 완화'],
    intakeGuide: '필요 시 섭취',
    precautions: ['졸림 유발 가능'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '200mg',
      nutrients: [{ name: 'L-테아닌', amount: '200mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 16000,
    quantity: 260,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 30,
    createdAt: '2026.02.02 02:07:00',
    updatedAt: '2026.02.02 02:07:00',
    mainId: 'blood_nattokinase',
    categoryId: 'blood_flow',
    name: '나토키나제',
    content: '혈액 흐름 개선에 도움',
    mainNutrients: ['나토키나제'],
    mainFunctions: ['혈행 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['혈액 응고 질환자 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '100mg',
      nutrients: [{ name: '나토키나제', amount: '100mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 23000,
    quantity: 180,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 31,
    createdAt: '2026.02.02 02:08:00',
    updatedAt: '2026.02.02 02:08:00',
    mainId: 'bone_vitamin_d',
    categoryId: 'bone_joint',
    name: '비타민 D',
    content: '뼈 건강과 칼슘 흡수에 도움',
    mainNutrients: ['비타민 D'],
    mainFunctions: ['뼈 건강', '면역 기능 보조'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '10µg',
      nutrients: [{ name: '비타민 D', amount: '10µg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 11000,
    quantity: 320,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 32,
    createdAt: '2026.02.02 02:09:00',
    updatedAt: '2026.02.02 02:09:00',
    mainId: 'general_mineral',
    categoryId: 'general',
    name: '멀티 미네랄',
    content: '하루 필수 미네랄 보충',
    mainNutrients: ['아연', '마그네슘', '셀레늄'],
    mainFunctions: ['기초 건강 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['중복 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1정',
      nutrients: [{ name: '미네랄 복합', amount: '-', dailyValue: '-' }],
    },
    seller_id: 1,
    price: 15000,
    quantity: 400,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 33,
    createdAt: '2026.02.02 02:10:00',
    updatedAt: '2026.02.02 02:10:00',
    mainId: 'diet_cla',
    categoryId: 'diet',
    name: 'CLA 공액리놀레산',
    content: '체지방 감소에 도움을 주는 지방산',
    mainNutrients: ['CLA'],
    mainFunctions: ['체지방 감소', '근육량 유지'],
    intakeGuide: '식후 섭취',
    precautions: ['과다 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1000mg',
      nutrients: [{ name: 'CLA', amount: '1000mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 19000,
    quantity: 250,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 34,
    createdAt: '2026.02.02 02:11:00',
    updatedAt: '2026.02.02 02:11:00',
    mainId: 'eye_bilberry',
    categoryId: 'eye',
    name: '빌베리 추출물',
    content: '눈 피로 완화와 시력 보호',
    mainNutrients: ['안토시아닌'],
    mainFunctions: ['눈 피로 완화', '시력 보호'],
    intakeGuide: '식후 섭취',
    precautions: ['임산부 상담 필요'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '160mg',
      nutrients: [{ name: '안토시아닌', amount: '36mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 21000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 35,
    createdAt: '2026.02.02 02:12:00',
    updatedAt: '2026.02.02 02:12:00',
    mainId: 'gut_aloe',
    categoryId: 'gut',
    name: '알로에 전잎',
    content: '장 기능 개선과 배변 활동 도움',
    mainNutrients: ['알로에'],
    mainFunctions: ['배변 활동 원활', '장 건강 개선'],
    intakeGuide: '취침 전 섭취',
    precautions: ['과다 섭취 시 설사'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '300mg',
      nutrients: [{ name: '알로에', amount: '300mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 12000,
    quantity: 280,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 36,
    createdAt: '2026.02.02 02:13:00',
    updatedAt: '2026.02.02 02:13:00',
    mainId: 'immune_propolis',
    categoryId: 'immune_fatigue',
    name: '프로폴리스',
    content: '항산화 및 면역 기능 증진',
    mainNutrients: ['프로폴리스'],
    mainFunctions: ['면역력 강화', '항산화'],
    intakeGuide: '식후 섭취',
    precautions: ['벌 알레르기 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '200mg',
      nutrients: [{ name: '프로폴리스', amount: '200mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 24000,
    quantity: 180,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 37,
    createdAt: '2026.02.02 02:14:00',
    updatedAt: '2026.02.02 02:14:00',
    mainId: 'skin_elastin',
    categoryId: 'skin_hair',
    name: '엘라스틴',
    content: '피부 탄력 유지에 도움',
    mainNutrients: ['엘라스틴'],
    mainFunctions: ['피부 탄력 개선'],
    intakeGuide: '식후 섭취',
    precautions: ['특이 체질 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '500mg',
      nutrients: [{ name: '엘라스틴', amount: '500mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 23000,
    quantity: 220,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 38,
    createdAt: '2026.02.02 02:15:00',
    updatedAt: '2026.02.02 02:15:00',
    mainId: 'women_calcium',
    categoryId: 'women',
    name: '여성 칼슘',
    content: '여성을 위한 뼈 건강 설계',
    mainNutrients: ['칼슘', '비타민D'],
    mainFunctions: ['골다공증 예방', '뼈 건강'],
    intakeGuide: '식후 섭취',
    precautions: ['중복 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '2정',
      nutrients: [{ name: '칼슘', amount: '700mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 17000,
    quantity: 260,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 39,
    createdAt: '2026.02.02 02:16:00',
    updatedAt: '2026.02.02 02:16:00',
    mainId: 'brain_magnesium',
    categoryId: 'brain',
    name: '마그네슘 L-트레오네이트',
    content: '집중력과 기억력 보조',
    mainNutrients: ['마그네슘'],
    mainFunctions: ['집중력 향상', '기억력 보조'],
    intakeGuide: '취침 전 섭취',
    precautions: ['설사 유발 가능'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '200mg',
      nutrients: [{ name: '마그네슘', amount: '200mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 26000,
    quantity: 180,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 40,
    createdAt: '2026.02.02 02:17:00',
    updatedAt: '2026.02.02 02:17:00',
    mainId: 'blood_coq10',
    categoryId: 'blood_flow',
    name: '코엔자임 Q10',
    content: '혈액순환과 항산화 지원',
    mainNutrients: ['코엔자임Q10'],
    mainFunctions: ['혈행 개선', '항산화'],
    intakeGuide: '식후 섭취',
    precautions: ['저혈압 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '100mg',
      nutrients: [{ name: '코엔자임Q10', amount: '100mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 28000,
    quantity: 170,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 41,
    createdAt: '2026.02.02 02:18:00',
    updatedAt: '2026.02.02 02:18:00',
    mainId: 'bone_msm',
    categoryId: 'bone_joint',
    name: 'MSM 식이유황',
    content: '관절 유연성과 통증 완화',
    mainNutrients: ['MSM'],
    mainFunctions: ['관절 건강', '연골 보호'],
    intakeGuide: '식후 섭취',
    precautions: ['위장 민감자 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1500mg',
      nutrients: [{ name: 'MSM', amount: '1500mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 21000,
    quantity: 240,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 42,
    createdAt: '2026.02.02 02:19:00',
    updatedAt: '2026.02.02 02:19:00',
    mainId: 'general_antioxidant',
    categoryId: 'general',
    name: '항산화 복합',
    content: '활력과 노화 방지 지원',
    mainNutrients: ['셀레늄', '비타민E'],
    mainFunctions: ['항산화', '세포 보호'],
    intakeGuide: '식후 섭취',
    precautions: ['중복 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1정',
      nutrients: [{ name: '항산화 복합', amount: '-', dailyValue: '-' }],
    },
    seller_id: 1,
    price: 16000,
    quantity: 320,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 43,
    createdAt: '2026.02.02 02:20:00',
    updatedAt: '2026.02.02 02:20:00',
    mainId: 'diet_chitosan',
    categoryId: 'diet',
    name: '키토산',
    content: '지방 흡수 억제에 도움',
    mainNutrients: ['키토산'],
    mainFunctions: ['지방 흡수 억제'],
    intakeGuide: '식전 섭취',
    precautions: ['갑각류 알레르기 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1000mg',
      nutrients: [{ name: '키토산', amount: '1000mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 15000,
    quantity: 300,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 44,
    createdAt: '2026.02.02 02:21:00',
    updatedAt: '2026.02.02 02:21:00',
    mainId: 'eye_vitamin_a',
    categoryId: 'eye',
    name: '비타민 A',
    content: '야간 시력과 눈 점막 건강',
    mainNutrients: ['비타민 A'],
    mainFunctions: ['시력 유지', '눈 건강'],
    intakeGuide: '식후 섭취',
    precautions: ['임산부 과다 섭취 금지'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '700µg',
      nutrients: [{ name: '비타민 A', amount: '700µg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 13000,
    quantity: 340,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 45,
    createdAt: '2026.02.02 02:22:00',
    updatedAt: '2026.02.02 02:22:00',
    mainId: 'gut_glutamine',
    categoryId: 'gut',
    name: 'L-글루타민',
    content: '장 점막 보호와 회복',
    mainNutrients: ['L-글루타민'],
    mainFunctions: ['장 점막 보호', '회복 촉진'],
    intakeGuide: '공복 섭취',
    precautions: ['신장 질환자 상담'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '5g',
      nutrients: [{ name: 'L-글루타민', amount: '5g', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 20000,
    quantity: 210,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 46,
    createdAt: '2026.02.02 02:23:00',
    updatedAt: '2026.02.02 02:23:00',
    mainId: 'immune_bcomplex',
    categoryId: 'immune_fatigue',
    name: '비타민 B콤플렉스',
    content: '에너지 대사와 피로 개선',
    mainNutrients: ['비타민 B군'],
    mainFunctions: ['피로 회복', '에너지 생성'],
    intakeGuide: '아침 식후 섭취',
    precautions: ['공복 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1정',
      nutrients: [{ name: '비타민 B군', amount: '-', dailyValue: '-' }],
    },
    seller_id: 1,
    price: 14000,
    quantity: 360,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 47,
    createdAt: '2026.02.02 02:24:00',
    updatedAt: '2026.02.02 02:24:00',
    mainId: 'skin_ceramide',
    categoryId: 'skin_hair',
    name: '세라마이드',
    content: '피부 장벽 강화',
    mainNutrients: ['세라마이드'],
    mainFunctions: ['보습 유지', '피부 장벽 강화'],
    intakeGuide: '식후 섭취',
    precautions: ['특이 체질 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '40mg',
      nutrients: [{ name: '세라마이드', amount: '40mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 22000,
    quantity: 230,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 48,
    createdAt: '2026.02.02 02:25:00',
    updatedAt: '2026.02.02 02:25:00',
    mainId: 'women_pms',
    categoryId: 'women',
    name: 'PMS 케어',
    content: '여성 주기 컨디션 관리',
    mainNutrients: ['마그네슘', '비타민 B6'],
    mainFunctions: ['여성 컨디션 개선'],
    intakeGuide: '주기 전 섭취',
    precautions: ['임산부 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1정',
      nutrients: [{ name: '복합 성분', amount: '-', dailyValue: '-' }],
    },
    seller_id: 1,
    price: 20000,
    quantity: 240,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 49,
    createdAt: '2026.02.02 02:26:00',
    updatedAt: '2026.02.02 02:26:00',
    mainId: 'brain_gaba',
    categoryId: 'brain',
    name: 'GABA',
    content: '스트레스 완화와 숙면 도움',
    mainNutrients: ['GABA'],
    mainFunctions: ['스트레스 완화', '수면 질 개선'],
    intakeGuide: '취침 전 섭취',
    precautions: ['졸림 유발'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '250mg',
      nutrients: [{ name: 'GABA', amount: '250mg', dailyValue: '100%' }],
    },
    seller_id: 1,
    price: 18000,
    quantity: 260,
    show: true,
    active: true,
    views: 0,
  },
  {
    _id: 50,
    createdAt: '2026.02.02 02:27:00',
    updatedAt: '2026.02.02 02:27:00',
    mainId: 'general_daily_pack',
    categoryId: 'general',
    name: '데일리 건강팩',
    content: '하루 한 포로 건강 관리',
    mainNutrients: ['비타민', '미네랄'],
    mainFunctions: ['종합 건강 관리'],
    intakeGuide: '아침 식후 섭취',
    precautions: ['중복 섭취 주의'],
    storage: '서늘한 곳',
    nutritionInfoExample: {
      servingSize: '1포',
      nutrients: [{ name: '종합 영양', amount: '-', dailyValue: '-' }],
    },
    seller_id: 1,
    price: 30000,
    quantity: 200,
    show: true,
    active: true,
    views: 0,
  },
];

// 이미지 URL 자동 연결
const productsWithImages = products.map((p) => ({
  ...p,
  imageUrl: categoryImages[p.categoryId] || '/images/category/general.png',
}));

async function main() {
  const client = new MongoClient(process.env.MONGO_URI);
  await client.connect();
  const db = client.db('febc15-final05-ecad');
  const collection = db.collection('product');

  // 기존 데이터 삭제 (테스트용)
  await collection.deleteMany({});

  // 데이터 삽입
  const result = await collection.insertMany(productsWithImages);
  console.log(`${result.insertedCount}개의 상품이 삽입되었습니다.`);

  await client.close();
}

main().catch(console.error);
